version: '3'
services:
  sample:
    image: jetty:9.4-jre8
    ports:
      - '8080:8080'
    volumes:
      - ./target/spring-1.0-SNAPSHOT.war:/var/lib/jetty/webapps/ROOT.war
      - ./ext:/var/lib/jetty/lib/ext
